import * as React from 'react';
import CssBaseline from '@mui/material/CssBaseline';
import Grid from '@mui/material/Grid';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
import GitHubIcon from '@mui/icons-material/GitHub';
import LinkedInIcon from '@mui/icons-material/LinkedIn';
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme';
import Header from './Header';
import FeaturedPost from './FeaturedPost';
import Main from './Main';
import Footer from './Footer';
import post1 from "./blog-post/n8n_llama.md";
import post2 from "./blog-post/ml_model_package.md";
import post3 from "./blog-post/test_long_post.md";
import post4 from "./blog-post/test_docker_ml.md";
import ProfileImage from './img/Gigi_Studio_ghibli_style_close_up_of_a_womans_face_with_black_2.jpg'

const socialLinks = [
  { name: 'GitHub', icon: GitHubIcon, url: "https://github.com/gigifokchiman" },
  { name: 'LinkedIn', icon: LinkedInIcon, url: "https://www.linkedin.com/in/gigifokcm/" },
];

const featuredPosts = [
  {
    title: 'About Gigi Fok',
    description:
      'A data scientist and machine learning engineer who loves to share her thoughts and experiences. I started my blog journey to make ML accessible by everyone in 2024.',
    image: ProfileImage,
    imageLabel: "Generated by AI with Gigi's real image",
    social: socialLinks,
  },
];

const posts = [post4, post3, post1, post2];

export default function Blog() {
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Box sx={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
        <Container maxWidth="lg">
          <Header title="Home" sections={[]} />
          <main>
            <Grid container spacing={4}>
              {featuredPosts.map((post) => (
                <FeaturedPost key={post.title} post={post} />
              ))}
            </Grid>
            <Grid container spacing={5} sx={{ mt: 3 }}>
              <Main title="Recent posts" posts={posts} />
            </Grid>
          </main>
        </Container>
        <Footer social={socialLinks} />
      </Box>
    </ThemeProvider>
  );
}
